BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "rp3_custom"
BBFILE_PATTERN_rp3_custom = "^${LAYERDIR}/"
BBFILE_PRIORITY_rp3_custom = "10"

LAYERSERIES_COMPAT_rp3_custom = "whinlatter"
LAYERDEPENDS_rp3_custom = "raspberrypi"
