
DISTRO = "aarons-distro"
DISTRO_NAME = "My minimal test distro for the raspberypi"
DISTRO_VERSION = "1.0"

PREFERRED_VERSION_linux-raspberrypi ?= "6.12%"
PACKAGE_CLASSES ?= "package_ipk"

DISTRO_FEATURES ?= "ipv4 ipv6 usbhost wifi sysvinit"

INIT_MANAGER = "mdev-busybox"

LICENSE_FLAGS_ACCEPTED = "synaptics-killswitch"

IMAGE_INSTALL:append = " \
    packagegroup-core-boot \
    kernel-modules \
    linux-firmware \
    wpa-supplicant \
    connman \
    connman-client \
    dropbear \
    usbutils \
    psplash \
"
